server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:8081/
          predicates:
            - Path= /employee/**
        - id: department-service
          uri: http://localhost:8082/
          predicates:
            - Path= /department/**

  config:
    import: "optional:configserver:http://localhost:8088"

management:
  tracing:
    sampling:
      probability: 1.0
